CREATE TABLE t_player (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	sex INT NOT NULL DEFAULT 0, -- 0:male, 1:female, 2:unknow
	age INT NOT NULL DEFAULT 0,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
