version: '2'
services:
    redis:
      image: redis:7.0.5
      container_name: redis
      ports:
        - "6379:6379"
      volumes:
        # - /mnt/redis/config/redis.conf:/etc/redis/redis.conf 
        - /Users/maxiongmiao/dockers/redis/config/redis_6379.conf:/etc/redis/redis.conf 
        - /Users/maxiongmiao/dockers/redis/data:/data
      command: redis-server /etc/redis/redis.conf 
      privileged: true
